services:
  memgraph:
    image: memgraph/memgraph
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      MEMGRAPH_USER: memgraph
      MEMGRAPH_PASSWORD: test

  postgresql:
    image: postgres
    container_name: postgres
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      timeout: 1s
      retries: 60
    restart: always

    # server:
    #   build:
    #     dockerfile: Dockerfile
    #     context: .
    #   ports:
    #     - "8000:8000"
    #   volumes:
    #     - .env:/app/.env
    #   depends_on:
    #     postgresql:
    #       condition: service_healthy
    #   stop_signal: SIGINT
