services:
  memgraph_db:
    image: memgraph/memgraph
    container_name: memgraph
    ports:
      - "7687:7687"
      - "7444:7444"
    environment:
      MEMGRAPH_USER: memgraph
      MEMGRAPH_PASSWORD: test

  memgraph_lab:
    image: memgraph/lab
    container_name: lab
    ports:
      - "3000:3000"

  postgres_db:
    image: postgres
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "postgres" ]
      interval: 1s
      timeout: 1s
      retries: 60
    restart: always

  orchestrator:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./orchestrator
    ports:
      - "${ORCHESTRATOR_PORT}:${ORCHESTRATOR_PORT}"
    volumes:
      - .env:/app/.env
    depends_on:
      postgres_db:
        condition: service_healthy
    stop_signal: SIGINT

  agent:
    build:
      dockerfile: Dockerfile
      context: .
    command: ./agent
    volumes:
      - .env:/app/.env
    stop_signal: SIGINT

